// All Farsi text constants for the app
export const TEXT = {
  auth: {
    signIn: 'ورود',
    signUp: 'ثبت‌نام',
    email: 'ایمیل',
    password: 'رمز عبور',
    name: 'نام',
    appName: 'گلدیفای',
    appTagline: 'محاسبه کن چقدر طول می‌کشه تا چیزی که می‌خوای رو بخری',
    alreadyHaveAccount: 'قبلاً ثبت‌نام کردی؟ وارد شو',
    noAccount: 'حساب کاربری نداری؟ ثبت‌نام کن',
    fillAllFields: 'لطفاً همه‌ی فیلدها رو پر کن',
    enterName: 'لطفاً نامت رو وارد کن',
    invalidEmail: 'لطفاً ایمیل معتبر وارد کن',
  },
  calculate: {
    title: 'محاسبه طلا',
    subtitle: 'قیمت محصول رو وارد کن تا معادل طلای اون رو ببینی',
    goldPrice: 'قیمت طلای ۱۸ عیار',
    perGram: 'هر گرم',
    fetchingGoldPrice: 'در حال دریافت قیمت طلا...',
    goldPriceError: 'خطا در دریافت قیمت طلا',
    addNewProduct: 'افزودن محصول جدید',
    newProduct: 'محصول جدید',
    productName: 'نام محصول',
    productNamePlaceholder: 'مثلاً: گوشی موبایل',
    price: 'قیمت (تومان)',
    goldEquivalent: 'معادل طلا',
    milligrams: 'میلی‌گرم',
    grams18K: 'گرم طلای ۱۸ عیار',
    soot: 'سوت',
    sootDescription: 'سوت (واحد سنتی ایرانی برای طلا)',
    addToWishlist: 'افزودن به علاقه‌مندی‌ها',
    saveWithoutWishlist: 'ذخیره بدون افزودن',
    wishlistHelp: 'با افزودن به علاقه‌مندی‌ها می‌تونی پیشرفت خریدت رو بر اساس طلا دنبال کنی',
    enterValidPrice: 'لطفاً قیمت معتبری وارد کن',
    enterProductAndPrice: 'لطفاً نام و قیمت محصول رو وارد کن',
    productAdded: 'انجام شد',
    addedToWishlist: 'محصول به علاقه‌مندی‌ها اضافه شد',
    productSaved: 'محصول ذخیره شد',
    addProductError: 'خطا در افزودن محصول',
    priceMovement: 'تغییرات قیمت',
  },
  wishlist: {
    title: 'علاقه‌مندی‌ها',
    subtitle: 'پیشرفت خرید محصولاتت رو با طلا دنبال کن',
    noItems: 'هنوز هیچ محصولی به علاقه‌مندی‌ها اضافه نکردی',
    goldEquivalent: 'معادل طلا:',
    savedGold: 'طلای ذخیره‌شده:',
    remaining: 'باقی‌مانده:',
    milligrams: 'میلی‌گرم',
    toman: 'تومان',
    addGold: 'افزودن طلا',
    goalReached: '✓ هدف به دست اومد!',
    removeProduct: 'حذف محصول',
    removeConfirm: (name: string) => `آیا مطمئنی می‌خوای «${name}» رو حذف کنی؟`,
    cancel: 'انصراف',
    remove: 'حذف',
    goldAmount: 'مقدار طلا (گرم)',
    enterValidAmount: 'لطفاً مقدار معتبری وارد کن',
    goldUpdated: 'طلای ذخیره‌شده به‌روزرسانی شد',
    updateError: 'خطا در به‌روزرسانی',
    deleteError: 'خطا در حذف محصول',
    save: 'ذخیره',
  },
  profile: {
    title: 'تنظیمات',
    subtitle: 'مدیریت حساب و تنظیمات شما',
    financialSettings: 'تنظیمات مالی',
    financialDescription: 'درآمد و نرخ پس‌اندازت رو وارد کن تا زمان رسیدن به هدفت محاسبه بشه',
    monthlySalary: 'درآمد ماهانه (تومان)',
    savingsPercentage: 'درصد پس‌انداز ماهانه',
    monthlySavingsAmount: 'مقدار پس‌انداز ماهانه',
    saveFinancials: 'ذخیره تنظیمات',
    financialsUpdated: 'تنظیمات مالی به‌روزرسانی شد',
    enterValidSalary: 'لطفاً درآمد معتبری وارد کن',
    enterValidPercentage: 'درصد باید بین ۱ تا ۱۰۰ باشه',
    updateError: 'خطا در به‌روزرسانی تنظیمات',
    theme: 'تم',
    themeDescription: 'انتخاب حالت تاریک یا روشن',
    darkMode: 'حالت تاریک',
    lightMode: 'حالت روشن',
    signOut: 'خروج از حساب',
  },
  timeline: {
    canBuyIn: (time: string) => `می‌تونی توی ${time} بخری`,
    canBuy: 'می‌تونی بخری توی مدت',
    monthsToSave: (count: number) => `${count} ماه دیگه`,
    yearsToSave: (years: number, months: number) => `${years} سال و ${months} ماه`,
    daysToSave: (count: number) => `${count} روز دیگه`,
    goalReached: 'هدف به دست اومده!',
    setSalaryFirst: 'اول درآمدت رو توی تنظیمات وارد کن',
    estimatedDate: (date: string) => `تاریخ تخمینی: ${date}`,
  },
  time: {
    year: 'سال',
    years: 'سال',
    month: 'ماه',
    months: 'ماه',
    day: 'روز',
    days: 'روز',
    hour: 'ساعت',
    hours: 'ساعت',
    minute: 'دقیقه',
    minutes: 'دقیقه',
    second: 'ثانیه',
    seconds: 'ثانیه',
  },
  navigation: {
    calculate: 'محاسبه',
    wishlist: 'علاقه‌مندی‌ها',
    history: 'پس‌انداز',
    settings: 'تنظیمات',
  },
  history: {
    title: 'پس‌انداز',
    subtitle: 'پیگیری پس‌اندازهای ماهانه و پیشرفت مالی',
    totalMoney: 'کل پول پس‌انداز شده',
    totalGoldSaved: 'کل طلای پس‌انداز شده',
    totalEntries: 'تعداد ثبت‌ها',
    addSavings: 'افزودن پس‌انداز',
    noLogs: 'هنوز هیچ پس‌اندازی ثبت نکردی',
    moneySaved: 'پول پس‌انداز شده',
    goldSaved: 'طلای پس‌انداز شده',
    for: 'برای',
    deleteTitle: 'حذف پس‌انداز',
    deleteConfirm: 'آیا مطمئنی می‌خوای این پس‌انداز رو حذف کنی؟',
    deleted: 'پس‌انداز حذف شد',
    deleteError: 'خطا در حذف پس‌انداز',
    savingsType: 'نوع پس‌انداز',
    money: 'پول',
    gold: 'طلا',
    amount: 'مقدار (تومان)',
    goldAmount: 'مقدار (گرم)',
    amountPlaceholder: 'مثلاً: 5000000',
    goldAmountPlaceholder: 'مثلاً: 2.5',
    note: 'یادداشت',
    optional: 'اختیاری',
    notePlaceholder: 'یادداشتی درباره این پس‌انداز...',
    savingsAdded: 'پس‌انداز اضافه شد',
    addError: 'خطا در افزودن پس‌انداز',
    enterValidAmount: 'لطفاً مقدار معتبری وارد کن',
  },
  charts: {
    priceHistory: 'تاریخچه قیمت طلا',
    currentPrice: 'قیمت فعلی',
    change: (days: number) => `تغییرات ${days} روزه`,
    loading: 'در حال بارگذاری نمودار...',
    noData: 'اطلاعات نمودار موجود نیست',
    calculatedPriceMovement: 'تغییرات قیمت محاسبه شده',
  },
  common: {
    save: 'ذخیره',
    cancel: 'انصراف',
    delete: 'حذف',
    edit: 'ویرایش',
    loading: 'در حال بارگذاری...',
    error: 'خطا',
    success: 'انجام شد',
    ok: 'باشه',
    toman: 'تومان',
    gram: 'گرم',
    month: 'ماه',
  },
};

// Utility function to format numbers in Farsi
export const formatNumber = (num: number): string => {
  return new Intl.NumberFormat('fa-IR').format(Math.round(num));
};

// Utility function to format dates in Farsi (Persian/Jalali calendar)
export const formatDate = (dateString: string): string => {
  const date = new Date(dateString);
  return new Intl.DateTimeFormat('fa-IR-u-ca-persian', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }).format(date);
};

// Utility function to format dates in short format (for charts)
export const formatDateShort = (dateString: string): string => {
  const date = new Date(dateString);
  return new Intl.DateTimeFormat('fa-IR-u-ca-persian', {
    month: 'short',
    day: 'numeric',
  }).format(date);
};
